version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: interview
    build:
      context: .
    image: interview
    depends_on:
      - db
    ports:
      - '5000:5000'
    environment:
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_USER: postgres
      PSQL_PASSWORD: postgres
      PSQL_DATABASE: postgres
    links:
      - "db:postgres"
volumes:
  db:
    driver: local